name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}
          registry: rg.fr-par.scw.cloud

      - name: Build & push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          tags: tthsympa/slot:latest
      - run: docker push rg.fr-par.scw.cloud/tthsympa/slot:latest

  deploy:
    name: Deploy Docker image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy & run throught SSH
        uses: fifsky/ssh-action@v0.0.4
        env:
          REGISTRY: rg.fr-par.scw.cloud
          TOKEN: ${{ secrets.SCW_SECRET_TOKEN }}
          PORT: 5000
        with:
          command: |
            docker login ${{ env.REGISTRY }}/tthsympa -u nologin -p ${{ env.TOKEN }}
            docker pull ${{ env.REGISTRY }}/tthsympa/slot:latest
            docker container stop tthsympa_slot
            docker container rm tthsympa_slot
            docker run -d --name tthsympa_slot -p ${{ env.PORT }}:${{ env.PORT }} ${{ env.REGISTRY }}/tthsympa/slot:latest
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
